on: 
  push:
    paths:
      - 'corne/**'
      - '.github/workflows/build-corne.yml'
  workflow_dispatch:

jobs:
  build:
  - name: Build Chocofi
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    working-directory: corne
