on: 
  push:
    paths:
      - 'cradio/**'
      - '.github/workflows/build-cradio.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: cradio
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
